[0m23:13:30.979111 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000290622A1FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000290622A3E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000290622CB9D0>]}


============================== 23:13:30.982124 | b7b8f835-715f-4424-90d2-91e63b5df4a5 ==============================
[0m23:13:30.982124 [info ] [MainThread]: Running with dbt=1.7.7
[0m23:13:30.982124 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\roulB\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select .\\models\\example\\fact_part.sql', 'send_anonymous_usage_stats': 'True'}
[0m23:13:30.982124 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\roulB\Desktop\vs_cli\git_features\vs360\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:13:30.990177 [debug] [MainThread]: Command `dbt run` failed at 23:13:30.990177 after 0.12 seconds
[0m23:13:30.990177 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000290619A88D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002905B99C090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029061EC6B10>]}
[0m23:13:30.990177 [debug] [MainThread]: Flushing usage events
[0m20:28:46.078514 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245F4AD01D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245F4AF7F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245F52C6F10>]}


============================== 20:28:46.088055 | 49d1e9c6-b94d-4a88-ad8a-c62db4520c90 ==============================
[0m20:28:46.088055 [info ] [MainThread]: Running with dbt=1.7.7
[0m20:28:46.093366 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\roulB\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m20:28:46.095526 [info ] [MainThread]: dbt version: 1.7.7
[0m20:28:46.096539 [info ] [MainThread]: python version: 3.11.9
[0m20:28:46.101766 [info ] [MainThread]: python path: C:\Users\roulB\Desktop\vs_cli\env\Scripts\python.exe
[0m20:28:46.104786 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m20:28:52.137374 [info ] [MainThread]: Using profiles dir at C:\Users\roulB\.dbt
[0m20:28:52.137374 [info ] [MainThread]: Using profiles.yml file at C:\Users\roulB\.dbt\profiles.yml
[0m20:28:52.137374 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\roulB\Desktop\vs_cli\git_features\vs360\dbt_project.yml
[0m20:28:52.141805 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m20:28:52.145260 [debug] [MainThread]: Command `dbt debug` failed at 20:28:52.145260 after 6.17 seconds
[0m20:28:52.145260 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245F41B2150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245F4B88FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024600253390>]}
[0m20:28:52.145260 [debug] [MainThread]: Flushing usage events
